### PR TITLE
Exit with return code 1 on retriggers if test failed

### PR DESCRIPTION
**Pull request by juliogonzalez**

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Whoooooops, my failure for not running rake before issue the PR.

However this error is present at master as well.

@MalloZup please have a look: https://travis-ci.org/openSUSE/gitbot/builds/280019585?utm_source=github_status&utm_medium=notification

**Comment by MalloZup** [comment]
@juliogonzalez  i"m fixing the travis no pb

**Comment by juliogonzalez** [comment]
@MalloZup keep in mind it's failing locally for me as well (in case it helps)

**Comment by MalloZup** [comment]
yop it will succed soon :rocket:

**Pull request merged**
